### ISSUE TITLE
any chance getting these updated to latest node version?

### ISSUE THREAD

**Issue by agauniyal** [james2doyle/sublime-node-snippets#5]

**Comment by james2doyle** [comment]
Yeah that can happen. Do you happen to know which APIs are outdated or changed?

**Comment by agauniyal** [comment]
I'm in process of learning scraping with node so I'll soon compare against stable v5 and report back :smile:

**Comment by james2doyle** [comment]
I have an example of how to scape the docs via a JS script for the browser: https://github.com/james2doyle/sublime-node-snippets#adding-new-snippets
