### ISSUE TITLE
Remove popular module completions

### ISSUE THREAD

**Issue by fnky** [james2doyle/sublime-node-snippets#6]
Rather than providing completions for lodash, underscore and async as part of this package—which would also require them to be updated regularly—I'd suggest removing those from this package as there are already up-to-date and much improved snippet packages for these.

This would help to avoid conflict/mashup, having to update the snippets and also make more clarity to the intention of this package—providing completions for Node core modules.

**Comment by james2doyle** [comment]
Yeah that sounds good. Can you make those changes?

**Comment by fnky** [comment]
Sure
